openapi: 3.0.3
info:
  version: 0.0.1
  title: REST Intro Sample Application
  description: A small sample API to grasp the basics of the OpenAPI Specification
servers:
  - url: http://localhost:8080

paths:
  # https://swagger.io/specification/#paths-object


# components contain reusable definitions
# https://swagger.io/specification/#components-object
components:
  schemas:
    ponyDto:
      description: a pony
      properties:
        name:
          type: string
        color:
          type: string
    SampleError:
      description: Sample springboot error
      properties:
        timestamp:
          type: string
          example: 2022-02-28T14:13:56.466
          format: date-time
        status:
          type: number
          example: 404
        error:
          type: string
          example: Not Found
        path:
          type: string
          example: /api/nonexistent
          pattern: "/.+"
