openapi: 3.0.3
info:
  version: 0.0.1
  title: M320 Car Api
  description: M320 CRUD + OpenAPI, Made by Elias and Lorenz
servers:
  - url: http://localhost:8080

paths:
  /api/cars:
    get:
      summary: returns all cars
      operationId: getAllCars
      responses:
        200:
          description: A list of all cars in the system
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/car'
    post:
      summary: Adds a car to the list
      requestBody:
        description: The car to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/car'
      responses:
        200:
          description: returns the added car
          content:
            application/json:
              schema:
                type: object #/components/schemas/car
                example:
                  - { "id": "abc123-abc123", "brand": "Volkswagen", "name": "Golf", "color": "blue" }
  /api/cars/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: The ID of the car to retrieve
          required: true
          schema:
            type: string
      summary: returns a car using id
      operationId: getCarsByID
      responses:
        200:
          description: The car with the id of the parameter
          content:
            application/json:
              schema:
                type: object #/components/schemas/car
                example:
                  - { "id": "abc123-abc123", "brand": "Volkswagen", "name": "Golf", "color": "blue" }
    put:
      parameters:
        - name: id
          in: path
          description: The ID of the car to retrieve
          required: true
          schema:
            type: string
      responses:
        200:
          description: The updated car
          content:
            application/json:
              schema:
                type: object #/components/schemas/car
                example:
                  - { "id": "abc123-abc123", "brand": "Volkswagen", "name": "Golf", "color": "blue" }
    delete:
      parameters:
        - name: id
          in: path
          description: The ID of the car to retrieve
          required: true
          schema:
            type: string
      responses:
        200:
          description: No Content

components:
  schemas:
    car:
      description: car
      properties:
        id:
          type: string
          example: a5c68e74-96df-4238-bc44-e96b7864fe8c
        createTimestamp:
          type: string
          example: 2024-12-02T08:11:32.3263381+01:00
          format: date-time
        brand:
          type: string
          example: Mercedes
        model:
          type: string
          example: G-Klasse
        color:
          type: string
          example: blue
        year:
          type: number
          example: 2015
          format: year
        engine:
          type: string
          example: Three Cylinder
        ps:
          type: string
          example: 85
    SampleError:
      description: Sample springboot error
      properties:
        timestamp:
          type: string
          example: 2022-02-28T14:13:56.466
          format: date-time
        status:
          type: number
          example: 404
        error:
          type: string
          example: Not Found
        path:
          type: string
          example: /api/nonexistent
          pattern: "/.+"
